site_name: Offset
docs_dir: docs
nav:
    - Home: index.md
    - Tutorial: tutorial.md
    - Theory: theory.md
    - Network: network.md
    - Contributing: contributing.md

markdown_extensions:
  - footnotes

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - rust
