[package]
name = "offset-lockfile"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]

cluFlock = "1.2.5"

[dev-dependencies]

tempfile = "3.1.0"
